### ISSUE TITLE
Icons break build after upgrading to a Vite versions greater than 2.0.0-beta.52

### ISSUE THREAD

**Issue by juan267** [antfu/vite-plugin-icons#11]
Problem: 

If you update to any version of Vite greater than 2.0.0-beta.52 the following error will start appearing 

<img width="1436" alt="Screen Shot 2021-01-31 at 10 41 59" src="https://user-images.githubusercontent.com/8763740/106389394-0fc71a80-63b1-11eb-9842-45eb4a21dbdf.png">

This error comes from the components being generated by this plugin: 

<img width="1440" alt="Screen Shot 2021-01-31 at 10 42 31" src="https://user-images.githubusercontent.com/8763740/106389407-1fdefa00-63b1-11eb-8335-825a02d766b5.png">

I'm not sure if this is a vite-plugin-icons issue or if something got broken is Vite in the latest releases. Given that only broken components are the icon ones I decided to post this issue here first. Thanks for the hard work on this amazing plugin!

**Comment by antfu** [comment]
It works for me with 2.0.0-beta.60. Can you check again?

**Comment by juan267** [comment]
@antfu you are right I try it with a clean install of vitesse and it worked. Don't know what's getting broken on my build. Thanks for looking at it 👍
