### ISSUE TITLE
Icons get "transform: translateY(-5%);" by default

### ISSUE THREAD

**Issue by Mvsvh** [antfu/vite-plugin-icons#13]
I was wondering why icons get "transform: translateY(-5%) by default. Is this intended? Or is intrinsic to the icon packs?

![image](https://user-images.githubusercontent.com/19476943/108206666-fd760c00-7126-11eb-9c2a-1eacadc9bf89.png)

**Comment by antfu** [comment]
Yes, it's by design. You can configure it via:

https://github.com/antfu/vite-plugin-icons/blob/0e6cd82b8df806ecbbbefdb48bbab79873c5a46e/src/types.ts#L12-L14

**Comment by NoelDeMartin** [comment]
Hey, I'm curious, what's the reason for having these defaults? I just spend some time figuring out why an icon didn't spin using tailwind's `animate-spin` class, and I realized this was the issue.

**Comment by antfu** [comment]
@NoelDeMartin  It's removed in the latest version. Sorry for causing trouble.
