### ISSUE TITLE
Can't load icons with vitepress

### ISSUE THREAD

**Issue by ahawkclint** [antfu/vite-plugin-icons#15]
Hey with the latest vitepress the icons can't install.  Tried both options with no avail.  I just get a blank page.  

```
    "vite-plugin-icons": "^0.2.2",
    "vite-plugin-components": "^0.6.12",
    "@iconify/json": "^1.1.306"
```

Also I can't update vite-plugin-windicss to the latest version and have it work with vitepress. The latest version that works is 

```
    "vite-plugin-windicss": "^0.1.9",
    "vitepress": "^0.12.2"
```

Thanks for the great work.

**Comment by antfu** [comment]
Can't really help without a repro. Icons/componentss are working with Vitepress in VueUse's docs while WindiCSS plugin is working with Vitepress in WindiCSS' docs.

**Comment by gurupras** [comment]
Ah! For anyone else stuck on this, the crucial piece to this puzzle is the line: `include: [/\.vue$/, /\.vue\?vue/, /\.md$/],`.
With that, the resolver properly handles markdown files.

**Comment by userquin** [comment]
@gurupras it is about `unplugin-auto-import`?

https://github.com/antfu/unplugin-auto-import/issues/46
