### ISSUE TITLE
Typings for imported icons

### ISSUE THREAD

**Issue by JohnCampionJr** [antfu/vite-plugin-icons#16]
Hi!  Any way to have typings for imported icons?

```ts
import IconHome from '/@vite-icons/oi/home'
```

has the usual no typings found error.  
Have to import them rather than auto-import because they're being used in a list like this:
```ts
  { title: 'Home', icon: IconHome, link: '/' },
```

Trying to build a list of menu items like so
```ts
const items = reactive([
  // @ts-ignore
  { title: 'Home', icon: IconHome, link: '/' },
  { title: 'Counter', icon: IconCounter, link: '/Counter' },
  { title: 'Fetch data', icon: 'oi-list-rich', link: '/Fetch-Data' }
])
```

The string icons don't get imported as a component, and I can't figure out how to inline import them so I"m trying to just do the standard import but I get typing errors.  Open to ideas.

**Comment by antfu** [comment]
You can import them with `.vue`

```ts
import MdiAlarmOff from '/@vite-icons/mdi/alarm-off.vue'
```

```ts
// vue-shim.d.ts
declare module '*.vue' {
  import { defineComponent } from 'vue'
  const Component: ReturnType<typeof defineComponent>
  export default Component
}
```

**Comment by JohnCampionJr** [comment]
I actually tried that but couldn't get it to work in a Vitesse setup.
