### ISSUE TITLE
Icon names ending in numbers are not working

### ISSUE THREAD

**Issue by JohnCampionJr** [antfu/vite-plugin-icons#17]
It appears icons with ending numbers aren't working.

`<heroicons-outline-menu-alt-2 />`

gets converted to:

`/@id/@vite-icons/heroicons-outline/menu-alt2`

and of course fails to load without the missing hyphen

**Comment by sllee1004** [comment]
Hi @antfu,
I have issue to import a custom icon which is ended with number `<i-action-add-2>` The icon are inside the following folder path `~icons/action/add-2.svg`.
