### ISSUE TITLE
Elusive Icons `el-` prefix conflicts with element-plus component `el-` prefix

### ISSUE THREAD

**Issue by 3nuc** [antfu/vite-plugin-icons#19]
In [`element-plus`](https://github.com/element-plus/element-plus), components have the el- prefix (eg `<el-button>Hi</el-button>`

However, [Elusive Icons](https://iconify.design/icon-sets/el/) also has an `el-` prefix.

Example:
`<el-upload>` = Element Plus component -> https://element-plus.org/#/en-US/component/upload
`<el-upload>` = Elusive icons icon -> https://iconify.design/icon-sets/el/upload.html

Elusive Icons always takes precedence in this case.

eg. `<el-button>` looks for the "button" icon in Elusive Icons. The intention with writing <el-button> is rendering an Element Plus button but with vite-plugin-icons it's not possible, because the "el-" prefix is interpreted as an Elusive Icons prefix. The result is an error, because there's no `el-button` icon. `el-upload` is another case to consider, since `el-upload` is both a component and an icon.

[Repro in Vitesse](https://github.com/3nuc/tworzenie-aplikacji-sieciowych/blob/element-plus-conflict-repro/front/src/pages/upload.vue#L6) - install with npm install rather than pnpm (Link to branch and file with repro)

**Comment by antfu** [comment]
https://github.com/3nuc/tworzenie-aplikacji-sieciowych/blob/091e9c32c9ce4c77b5ba9423f37c03a808c09550/front/vite.config.ts#L55-L56

You can either add a prefix for icons (which is the default, but I prefer non-prefix in Vitesse). Or only enable certain icon collections

**Comment by 3nuc** [comment]
@antfu I just saw this in my config and wanted to close. Sorry for the trouble
For future visitors: https://github.com/3nuc/tworzenie-aplikacji-sieciowych/commit/8af7867055d227a72977b78e97e2936c46f4fb52
