### ISSUE TITLE
Cannot find module '@iconify/json'

### ISSUE THREAD

**Issue by nandordudas** [antfu/vite-plugin-icons#2]
I have got the same error yesterday like #1 and tried to reproduce, but got another errors.

Here is the example repo.

```sh
git clone https://github.com/nandordudas/vite-plugin-icons
cd vite-plugin-icons
pnpm i # or yarn
```

After manually installed `@iconify/json` got another error.

Node: v15.5.1
OS: Manjaro Linux x86_64

**Comment by antfu** [comment]
`@iconify/json` is a peer deps and you should install it as dev dependencies.
