### ISSUE TITLE
Icons aren't aligned correctly

### ISSUE THREAD

**Issue by FallDownTheSystem** [antfu/vite-plugin-icons#22]
Using the icons via the plugin and comparing them to the pasted in SVG, you can see the vertical alignment is wrong.

See 
```html
<i-tabler:arrow-narrow-left
	class="w-5 h-5"
/>
<svg
	xmlns="http://www.w3.org/2000/svg"
	aria-hidden="true"
	role="img"
	class="w-5 h-5"
	width="32"
	height="32"
	preserveAspectRatio="xMidYMid meet"
	viewBox="0 0 24 24"
>
	<g
		class="icon-tabler"
		fill="none"
		stroke="currentColor"
		stroke-width="2"
		stroke-linecap="round"
		stroke-linejoin="round"
	>
		<path d="M5 12h14" />
		<path d="M5 12l4 4" />
		<path d="M5 12l4-4" />
	</g>
</svg>
```

The only added part is the width and height classes.

See ![image](https://i.imgur.com/3lpjpka.png) for reference.
The latter arrow (direct SVG) is aligned correctly with the text, whereas the plugin icon is a little too high. I tried with a couple of different icon sets, so it's not just this specific icon.

**Comment by FallDownTheSystem** [comment]
I just looked at the code and it seems there's a default style
`'vertical-align: middle; transform: translateY(-5%);'`

I'm not sure why.

**Comment by antfu** [comment]
Removed the default in v0.5.0.
