### ISSUE TITLE
It  has unmet peer dependency "vue-template-compiler"

### ISSUE THREAD

**Issue by autumnalriver** [antfu/vite-plugin-icons#23]
When run install script, the commandline shows as follow:
```sh
warning " > vite-plugin-icons@0.5.0" has unmet peer dependency "vue-template-compiler@^2.6.12".
```

**Comment by chojnicki** [comment]
Can You @antfu remove this peer dependency or it's necessary evil due to Vue2 support? For Vue 3 it's just false alarm
