### ISSUE TITLE
Autoload libraries with dashes fails

### ISSUE THREAD

**Issue by xorik** [antfu/vite-plugin-icons#24]
Hi!

I didn't find how to load icons like those:
```
mdi-light:alarm
noto-v1:flag-for-flag-japan
```

If I write:
```html
<i-mdi-light-alarm></i-mdi-light-alarm>
```
it fails...

I took those names [here](https://icones.js.org/collection/all). It works for libraries without dashes 🤔

**Comment by antfu** [comment]
Can you provide more context?

**Comment by xorik** [comment]
Sorry.

So I have a vue/vite app. I search for icons on the website https://icones.js.org/. Then I add prefix `i-` and replace comma to dash, so I get something like
```html
<i-ic-twotone-directions-bus/>
```

Put it in template and it perfectly works.

But some icons e.g. `mdi-light:alarm` or `noto-v1:flag-for-flag-japan`  aren't work.
```html
<!--  This doesn't work  -->
<i-noto-v1-flag-for-flag-japan/>
```

I think this is because the `noto-v1` contains a dash symbol, so parser gets confused.

So `App.vue`:
```vue
<template>
  <h3>Hello vite</h3>

  <div id="icons">
    <!--  This works  -->
    <i-ic-twotone-directions-bus/>

<!--  This doesn't work  -->
<!--    <i-noto-v1-flag-for-flag-japan/>-->
  </div>
</template>


<style>
#icons > * {
  font-size: 100px;
  padding: 10px;
}
</style>
```

`vite.config.js`:
```js
import Vue from '@vitejs/plugin-vue'
import Components from 'vite-plugin-components'
import ViteIcons, { ViteIconsResolver } from 'vite-plugin-icons'

export default {
  plugins: [
    Vue(),
    Components({
      customComponentResolvers: ViteIconsResolver(),
    }),
    ViteIcons(),
  ],
}
```

I hope it's clear now.

**Comment by antfu** [comment]
Ah, I see, it's indeed a bug. Could do that later, or if you would like to give a try, I am happy to see the PR. Thanks!

**Comment by xorik** [comment]
@antfu I'd like to help, but I have no idea how to debug plugins like that. Any suggestions how to start?

**Comment by antfu** [comment]
Actually, looks like all we need to do is to update the data source
https://github.com/antfu/vite-plugin-icons/blob/59a8ce431641ea211d654795fb1310771fe3dc18/src/resolver.ts#L36

I will do that now

**Comment by xorik** [comment]
Thank you for the quick fix!
