### ISSUE TITLE
TS issue - Ambient module declaration cannot specify relative module name

### ISSUE THREAD

**Issue by theoephraim** [antfu/vite-plugin-icons#25]
Things are ok during development but I'm running into this issue when running `vue-tsc --noEmit` (as part of my build script).

I'm getting this issue:
```
node_modules/vite-plugin-icons/client.d.ts:9:16 - error TS2436: Ambient module declaration cannot specify relative module name.

9 declare module '/@vite-icons/*' {
```
It appears the TS compiler does not like declaring a module name starting with a "/"

Any ideas what's going on?

My tsconfig file:
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "baseUrl": "./",
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "lib": ["esnext", "dom"],
    "types": ["vite/client", "node"],
    "paths": {
      "@/*": ["src/*"],
    }
  },
  "include": [
    "**/*.ts",
    "**/*.js",
    "src/**/*.tsx",
    "src/**/*.vue"
  ]
}
```

**Comment by theoephraim** [comment]
@antfu can you confirm if this issue is something unique to my setup or if you are seeing it as well?

I'm also curious why the declaration has that leading slash like that `'/@vite-icons/*'`?
Seems it has something to do with the resolver, but I'm unclear what's going on there exactly...

**Comment by antfu** [comment]
The leading slash indicates they're virtual modules. It seems to work fine on my side. Not that familiar with how `.d.ts` resolves, maybe someone else could help.

**Comment by theoephraim** [comment]
Can we just remove the extra declaration and expect users to use the `virtual:vite-icons/...` style instead?
I can't really find any other examples of plugins/libraries using a leading slash like this. I can only find examples where a leading slash is used in an alias, which TS knows how to handle.

I am curious though about why you're not seeing this error in your project or if there is something specific about my settings that is causing it. When I add `skipLibChecks` it goes away, so perhaps you have that option on?

**Comment by antfu** [comment]
At the very beginning of this package we use the `'/@vite-icons/*'` style due to the limitation of Vite, so it's more like for backward compatibility. If the removal of that entry solves your problem, I am happy to receive a PR for it.
