### ISSUE TITLE
gg系列的图标无法导入

### ISSUE THREAD

**Issue by cinob** [antfu/vite-plugin-icons#33]
首先感谢大佬为社区做出的贡献，许多项目我都用过，非常赞👍 

遇到的问题：
在使用过程中发现 https://iconify.design/icon-sets/gg/ 里的图标都无法导入，控制台报导入了不存在的模块

**Comment by antfu** [comment]
Do you have a reproduction? It seem to work on my side.

**Comment by cinob** [comment]
(。・＿・。)ﾉI’m sorry~  是 @iconify/json的版本问题， 感谢回复
