### ISSUE TITLE
Correct usage with heroicons + dynamic component syntax

### ISSUE THREAD

**Issue by armenr** [antfu/vite-plugin-icons#37]
Howdy! Still learning the ropes, and I promise I've read the documentation, so I promise I've spent a bit of time reading the documentation on both vite-plugin-icons + iconify...

Current setup - Using Vitesse boilerplate, no major changes to icons or components plugins configs:

```
    ViteComponents({
      // allow auto load markdown components under `./src/components/`
      extensions: ['vue', 'md'],

      // allow auto import and register components used in markdown
      customLoaderMatcher: id => id.endsWith('.md'),

      // generate `components.d.ts` for ts support with Volar
      globalComponentsDeclaration: true,

      // auto import icons
      customComponentResolvers: [
        HeadlessUiResolver(),
        ViteIconsResolver({
          componentPrefix: '',
          // enabledCollections: ['hero', 'mdi', 'carbon'],
        }),
      ],
    }),

    // https://github.com/antfu/vite-plugin-icons
    ViteIcons(),
```

In my Home Layout File `/src/layouts/home.vue`, I am working with a simple v-for loop. There is the following code:

```
<component :is="item.icon" class="mr-4 flex-shrink-0 h-6 w-6 text-indigo-300" aria-hidden="true" />
```

And I pass in an array of objects that look like this:

```
const navigation = [
  { name: 'Dashboard', href: '#', icon: 'heroicons-outline-x', current: true },
  { name: 'Team', href: '/hi/Armen', icon: 'heroicons-outline-home', current: false },
  { name: 'Projects', href: '#', icon: 'heroicons-outline:home', current: false },
  { name: 'Calendar', href: '#', icon: 'heroicons-outline:home', current: false },
  { name: 'Documents', href: '#', icon: 'heroicons-outline:home', current: false },
  { name: 'Reports', href: '#', icon: 'heroicons-outline:home', current: false },
]
```

Neither `heroicons-outline-*` or `heroicons-outline:*` appear to work.

I also tried this approach, but kept getting the following error --> `Module '"virtual:vite-icons/*"' has no exported member 'MenuAlt2Icon'. Did you mean to use 'import MenuAlt2Icon from "virtual:vite-icons/*"' instead?ts(2614)`

```
// import {
//   IconBellIcon,
//   IconCalendarIcon,
//   IconChartBarIcon,
//   FolderIcon,
//   HomeIcon,
//   InboxIcon,
//   MenuAlt2Icon,
//   UsersIcon,
//   XIcon,
// } from 'virtual:vite-icons/heroicons/outline'
```

I'm sure that whatever I'm doing wrong is probably something simple/stupid, but I'd appreciate any guidance you might be able to provide. 

Thank you!

**Comment by armenr** [comment]
Update:

Looks like this import strategy works:

```
import BellIcon from 'virtual:vite-icons/heroicons-outline/home'
import CalendarIcon from 'virtual:vite-icons/heroicons-outline/calendar'
import ChartBarIcon from 'virtual:vite-icons/heroicons-outline/chart-bar'
import FolderIcon from 'virtual:vite-icons/heroicons-outline/folder'
import HomeIcon from 'virtual:vite-icons/heroicons-outline/home'
import MenuAlt2Icon from 'virtual:vite-icons/heroicons-outline/menu-alt-2'
import InboxIcon from 'virtual:vite-icons/heroicons-outline/inbox'
import UsersIcon from 'virtual:vite-icons/heroicons-outline/users'
import XIcon from 'virtual:vite-icons/heroicons-outline/x'


const navigation = [
  { name: 'Dashboard', href: '#', icon: HomeIcon, current: true },
  { name: 'Team', href: '#', icon: UsersIcon, current: false },
  { name: 'Projects', href: '#', icon: FolderIcon, current: false },
  { name: 'Calendar', href: '#', icon: CalendarIcon, current: false },
  { name: 'Documents', href: '#', icon: InboxIcon, current: false },
  { name: 'Reports', href: '#', icon: ChartBarIcon, current: false },
]
```

So, my only question is: Is there a better/cleaner/automated/more concise way to do all of this importing and referencing?

**Comment by antfu** [comment]
If the icon names are finite and already known at the build time, I think your approach is the way to go. Named support is not supported because the modules are served virtually and on-demanded, been able to have named import for icons would require the module to bundle all the icons in the collection, which I think it's not ideal. But if you really want it, I guess you can write an inline plugin to transform the code and make it work magically.

For more dynamic icon loading, you might want to check https://github.com/antfu/purge-icons instead.

**Comment by zhuhaobam** [comment]
Is there any way to use it like this
I want to have a limited array to download the required icons in advance, so that the H function can be used freely
```
export function renderNIconWithIcons(icon: string, size?: number) {
  return () => h(NIcon, { size: size ?? 16 }, { default: () => h('div', { class: icon }) })
}
```

**Comment by zhuhaobam** [comment]
@antfu  
Please describe a problem on my previous floor
Is there an H function that uses rendering, such as menu icons
