### ISSUE TITLE
dynamic icon components

### ISSUE THREAD

**Issue by jacobclevenger** [antfu/vite-plugin-icons#5]
Is it possible to dynamically use icons?

I'm using the vitesse template and would previously use something like `<Icon :icon="myIconVariable" />` but now it seems like that no longer exists so I was wondering if it is still possible to do something like that. 

I tried something like this without much luck
```html
<template>
  <component :is="myIconVariable.replace(':', '-')" />
</template>

<script setup>
const myIconVariable = 'mdi:vuejs'
</script>
```

**Comment by antfu** [comment]
No, this plugin is designed to be used statically. Can you combine it with vite-plugin-purge-icons to have both SSR icons and runtime dynamic icons.

**Comment by jacobclevenger** [comment]
Oh okay, gotcha. I'll give that a shot, thanks!

**Comment by ngekoding** [comment]
> Oh okay, gotcha. I'll give that a shot, thanks!

Have you make it work with vite-plugin-purge-icons?

**Comment by antfu** [comment]
Due to the mechanism of how [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) works, there is no way to infer a component from a dynamic string. (`unplugin-icons` only resolved icons at build time)

The workarounds for this is:

```html
<IconA v-if="cond1"/> 
<IconB v-else-if="cond2"/>
<IconC v-else-if="cond3"/>
<IconD v-else />
```

Or

```ts
<script setup>
import MdiAlarm from '~icons/mdi/alarm'
import MdiAccount from '~icons/mdi/account'

const items = [
{
  name: 'Alarm',
  icon: MdiAlarm,
},
{
  name: 'Account',
  icon: MdiAccount,
}
]
</script>

<template>
  <div v-for="i of items">
    <component :is="i.icon"/>
  </div>
</template>
```

**Comment by husayt** [comment]
With autoImport one can achieve even more elegant solution. Use the same IconResolver you used in unplugin components:
```
  AutoImport({
      imports: ["vue"],
      resolvers: [
        IconsResolver({
          componentPrefix: "icon",
          enabledCollections: ["carbon", "mdi"],
        }),
      ],
      dts: "src/auto-imports.d.ts",
    }),
```

Then you don't need to even import and the above will look like this:
```
<script setup>
const items = [
{
  name: 'Alarm',
  icon: IconMdiAlarm,
},
{
  name: 'Account',
  icon: IconMdiAccount,
}
]
</script>

<template>
  <div v-for="i of items">
    <component :is="i.icon"/>
  </div>
</template>
```

**Comment by zhangchenna** [comment]
> AutoImport

你这么写没用吧

**Comment by r-priyam** [comment]
Alternatively [this component method can also be used](https://github.com/antfu/icones/blob/master/src/components/Icon.vue) to get the icons dynamically rendered using string. Is it advisable to use it? @antfu

**Comment by maxshadurskiy** [comment]
@husayt it works!

**Comment by leosin** [comment]
> Along with autoImport one can achieve even more elegant solution. Use the same IconResolver you used in unplugin components:
> 
> ```
>   AutoImport({
>       imports: ["vue"],
>       resolvers: [
>         IconsResolver({
>           componentPrefix: "icon",
>           enabledCollections: ["carbon", "mdi"],
>         }),
>       ],
>       dts: "src/auto-imports.d.ts",
>     }),
> ```
> 
> Then you don't need to even import and the above will look like this:
> 
> ```
> <script setup>
> const items = [
> {
>   name: 'Alarm',
>   icon: IconMdiAlarm,
> },
> {
>   name: 'Account',
>   icon: IconMdiAccount,
> }
> ]
> </script>
> 
> <template>
>   <div v-for="i of items">
>     <component :is="i.icon"/>
>   </div>
> </template>
> ```

Uncaught (in promise) ReferenceError: IconMdiAlarm is not defined

**Comment by m424m** [comment]
I don't think you need unplugin-icons for this at all. Here is what I did:

```vue
<template>
  <svg viewBox="0 0 24 24" class="icon" :class="{inline}" v-html="getIcon(`${style}-${name}`)"/>
</template>

<script setup>
import icons from '@iconify-json/ic/icons.json'

const props = defineProps({
  name: String,
  style: {
    type: String,
    default: 'baseline'
  },
  inline: Boolean
})

const getIcon = name => {
  const s = icons.icons?.[name]
  if (s?.body) return s.body
  else if (s?.parent) return getIcon(s.parent)
  else return null
}
</script>

<style lang="scss" scoped>
svg {
  display: block;
  width: 1.2em;
  height: 1.2em;

  &.inline {
    display: inline-block;
    vertical-align: top;
  }
}
</style>
```

And you only have to install the icon package (in my case it's `@iconify-json/ic`). Other icon packs may require different name formats, but the general idea is the same.

**Comment by blooddrunk** [comment]
Just found that `defineAsyncComponent` also won't work. Had to use `@iconify/vue` and `@iconify/utils` to render icons dynamically. Hope there would be a way eventually.

**Comment by overtrue** [comment]
https://github.com/iconify/iconify/tree/master/packages/vue

**Comment by lrstanley** [comment]
> [...]
> Uncaught (in promise) ReferenceError: IconMdiAlarm is not defined

Doing this on multiple sites at the moment without issues. May want to make sure you have explicitly enabled the collection via `enabledCollections`. Can't recall if the auto-import as non-component requires that or not, but I do have that in my config, and no issues.

**Comment by coderwyd** [comment]
> Due to the mechanism of how [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) works, there is no way to infer a component from a dynamic string. (`unplugin-icons` only resolved icons at build time)
> 
> The workarounds for this is:
> 
> ```
> <IconA v-if="cond1"/> 
> <IconB v-else-if="cond2"/>
> <IconC v-else-if="cond3"/>
> <IconD v-else />
> ```
> 
> Or
> 
> ```ts
> <script setup>
> import MdiAlarm from '~icons/mdi/alarm'
> import MdiAccount from '~icons/mdi/account'
> 
> const items = [
> {
>   name: 'Alarm',
>   icon: MdiAlarm,
> },
> {
>   name: 'Account',
>   icon: MdiAccount,
> }
> ]
> </script>
> 
> <template>
>   <div v-for="i of items">
>     <component :is="i.icon"/>
>   </div>
> </template>
> ```
How do I use it in vue jsx?

**Comment by transtone** [comment]
[unocss Icons preset](https://unocss.dev/presets/icons) is welcome.

**Comment by JACKZGGG** [comment]
我项目中涉及到大量icon，如果每一个icon都要一个vue文件，再导入那就太恶心了

**Comment by JACKZGGG** [comment]
> 与 autoImport 一起可以实现更优雅的解决方案。使用与拔出组件相同的 IconResolver：
> 
> ```
>   AutoImport({
>       imports: ["vue"],
>       resolvers: [
>         IconsResolver({
>           componentPrefix: "icon",
>           enabledCollections: ["carbon", "mdi"],
>         }),
>       ],
>       dts: "src/auto-imports.d.ts",
>     }),
> ```
> 
> 然后你甚至不需要导入，上面的内容将如下所示：
> 
> ```
> <script setup>
> const items = [
> {
>   name: 'Alarm',
>   icon: IconMdiAlarm,
> },
> {
>   name: 'Account',
>   icon: IconMdiAccount,
> }
> ]
> </script>
> 
> <template>
>   <div v-for="i of items">
>     <component :is="i.icon"/>
>   </div>
> </template>
> ```

谢谢，按照你的方法至少我不用再创建一个个vue文件了

**Comment by oktaykaypak** [comment]
I use vue 3 and vite, this is how it worked for me


```
const icon = shallowRef()
onMounted(() => {
  icon.value = defineAsyncComponent(() => import('virtual:icons/mdi/brush.svg'))
})
</script>

<template>
  <Component :is="icon" class="size-16" />
</template>
```
