### ISSUE TITLE
Add icons dynamically

### ISSUE THREAD

**Issue by alvarosaburido** [antfu/vite-plugin-icons#7]
Hi, awesome work with this plugins man, enjoying a lot playing around with `vueuse` and this one.

Which would be the approach to dynamically insert icons? Let's say I have a menu metadata in a js object and icon is one of the properties.

One option I guess would be to use `<component :is="menuitem.icon"> ` where `icon: IconAccountBox` .

Would make sense to add a component `<icon :name="carbon-icon" />` to the repo?

**Comment by antfu** [comment]
#5, you can use https://github.com/antfu/purge-icons for dynamic loading and this for statical bunding. Guess I should update the README about this 😅

**Comment by alvarosaburido** [comment]
I could also check if there was one opened already haha, but it will help yes hehe. Thanks

**Comment by antfu** [comment]
But yeah, maybe we could have a configure to bundle all the icons in a collection (but that's what I am trying to solve here 😅). You can give it a shot if that makes sense to you, I will help for sure :)

**Comment by antfu** [comment]
Made an issue to track on that.

**Comment by husayt** [comment]
> #5, you can use https://github.com/antfu/purge-icons for dynamic loading and this for statical bunding. Guess I should update the README about this 😅

@antfu with custom loader I guess we can achieve dynamic loading here too now.
