### ISSUE TITLE
any plans to support dynamic components ? 

### ISSUE THREAD

**Issue by amrbashir** [antfu/vite-plugin-icons#9]
I have a use case where I have a list of objects that contains the icon information so I tried using: 
```vue
<component :is="`i-${icon}`" />
```
but no luck and quite frankly I am not sure if it is even possible.

**Comment by antfu** [comment]
#5 #7 #8

**Comment by amrbashir** [comment]
Oh sorry for the inconvenience, I guess I should've searched the closed issues.
